### ISSUE TITLE
Add a random track to track queue

### ISSUE THREAD

**Issue by iluvatyr** [kimden/stk-code#9]
## Description
Right now it is possible to add a track to the track queue by issueing a command as admin, such as:
```
/admin queue push track_id
```
I think it would be great to be able to also push random tracks into the track queue. This could be done with a command in the following format:

```
/admin queue push random
```

**Comment by iluvatyr** [comment]
any news on this?

**Comment by kimden** [comment]
I planned to add this pretty long time ago but then I realized there are pretty many details here, probably due to me overcomplicating things (but I think it will be more functional then).
Examples of what I want to do are: specifying from which the random should pick the map (all maps, official maps, addons only, whether the random should be able to pick from the maps outside of common for everyone present), whether the map should be announced or kept secret like the default random option does (in case it's installed for everyone).

Some more advanced things I'd like to do are forbidding last $n$ played maps in the random (or generally in selection). Thinking about advanced things made me thinking about changing the queue a lot, I guess I'll return to it when I have more time.

For now, if I didn't forget it really well (I changed it last spring I guess), `/queue push -` should add to the map queue a random addon (of all installed on server), and `/queue push -addon` should do the same but for addons only. I guess it takes into account the current game mode on the server, but I don't really remember (in practice, it does). Not sure `-` is a good identifier for random things though, but it needs to be something special to not be confused with any possible new map id.

I still plan to continue working on it but the thing looks bigger than before...

**Comment by kimden** [comment]
I probably also should publish the list of things I want to change because it's so big it blows up my mind so I'm more scared to clearing it :D and also it's harder to explain what exactly I'm changing without it

**Comment by kimden** [comment]
I don't even remember when it changed (at least 3 months ago), but I guess for quite some time `/queue push random` works, with some other additions such as `/queue push random 8` which allows picking from 8 random tracks, for example.

I haven't bothered removing track selection for the case of 1 random map yet, because it affects the selection very much. I will add it an option for it later.

It's currently on branch command-manager-prototype and not on master, but as README.md says, it will be merged there too eventually.
